"""create_training_table

Revision ID: f61f3ab400f5
Revises: b3c4d5e6f7a8
Create Date: 2026-08-14 13:55:15.190181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61f3ab400f5'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_admin_role_menus', 'admin_role_menus', ['admin_role_id', 'admin_menu_id'])
    op.drop_index(op.f('ix_courses_category'), table_name='courses')
    op.drop_index(op.f('ix_courses_room_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_teacher_id'), table_name='courses')
    op.drop_index(op.f('ix_user_coupons_source_activity'), table_name='user_coupons')
    op.drop_index(op.f('ix_user_coupons_source_activity_coupon'), table_name='user_coupons')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('users', 'balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('uq_wallet_transactions_booking_refund_booking'), table_name='wallet_transactions', postgresql_where="((type)::text = 'booking_refund'::text)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_wallet_transactions_booking_refund_booking'), 'wallet_transactions', ['booking_id'], unique=True, postgresql_where="((type)::text = 'booking_refund'::text)")
    op.alter_column('users', 'balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.create_index(op.f('ix_user_coupons_source_activity_coupon'), 'user_coupons', ['source_activity_coupon_id'], unique=False)
    op.create_index(op.f('ix_user_coupons_source_activity'), 'user_coupons', ['source_activity_id'], unique=False)
    op.create_index(op.f('ix_courses_teacher_id'), 'courses', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_courses_room_id'), 'courses', ['room_id'], unique=False)
    op.create_index(op.f('ix_courses_category'), 'courses', ['category'], unique=False)
    op.drop_constraint('uq_admin_role_menus', 'admin_role_menus', type_='unique')
    # ### end Alembic commands ###
